account/urls.py
from django.contrib.auth import views as auth_view
from django.urls import re_path as url, path
from . import views


urlpatterns = [
    url(r'^password/$', views.change_password, name='change_password'),
    path('register/', views.register, name="register"),
    path('login/', views.user_login, name="login"),
    path('logout/', views.user_logout, name="logout"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('', views.dashboard, name='dashboard'),
    path('profile-detail/<int:pk>/',
         views.ProfileDetailView.as_view(), name="profile-detail"),
    path('forgot-password/', views.forgot_password, name="forgot-password"),
    path('reset-password-validate/<uidb64>/<token>/',
         views.reset_password_validate, name="reset-password-validate"),
    path('reset-password/', views.reset_password, name="reset-password"),
    path('edit-profile/<int:profile_pk>/',
         views.edit_profile, name="edit-profile"),
    path('change-password/', views.change_password, name="change-password"),
    path("exception/", views.page_403),
    # path('reset_password/', auth_view.PasswordResetView.as_view(),
    #      name="reset-password")

]

# urlpatterns+=[
#     path()
# ]

contact/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('all-contacts/', views.contacts_overview, name='all-contacts'),
    path('detail/<int:pk>/', views.ContactDetailView.as_view(),
         name="contact-detail"),
    path('search/', views.SearchView, name="search"),
    path('create/<int:pk>/', views.ContactCreateView.as_view(),
         name="create-contact"),
    path('update/<int:pk>/',
         views.ContactUpdateView.as_view(), name="update-contact"),
    path('delete/<int:pk>/',
         views.ContactDeleteView.as_view(), name="delete-contact"),
    path('favourite/<int:contact_pk>/',
         views.add_contact_as_favourite, name="favourite"),
    path('favourites/', views.list_favourites_contacts, name='favourite-contacts'),
    path('export-csv/<int:account_pk>/',
         views.generate_contact_csv, name='export-contacts'),
    path('import-csv/<int:account_pk>/',
         views.import_csv, name="import-contacts")
]

contact_mgt/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf.urls import (handler400, handler404, handler403, handler500)

handler500 = "account.views.page_500"
handler403 = "account.views.page_403"
# handler404 = "account.views.page_404"
handler400 = "account.views.page_400"
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(url='contact/')),
    path('contact/', include('contact.urls')),
    path('account/', include("account.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# style = "background: linear-gradient(90deg, hsla(217, 100%, 50%, 1) 0%, hsla(186, 100%, 69%, 1) 100%);"

account/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils.text import slugify
from django.contrib.auth.hashers import make_password
from django.dispatch import receiver
from django.db.models.signals import post_save, pre_save
# from .validators import UnicodeUsernameValidators

# Create your models here.


class MyAccountManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not username:
            raise ValueError("User must have a username")
        if not email:
            raise ValueError("User must have an email address")
        user = self.model(username=username, first_name=first_name,
                          last_name=last_name, email=self.normalize_email(email))
        # user.password = make_password(password)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password):
        user = self.create_user(first_name=first_name, last_name=last_name,
                                username=username, email=self.normalize_email(email), password=password)
        user.is_admin = True
        user.is_staff = True
        user.is_superadmin = True
        user.is_active = True
        user.save(using=self._db)

        return user


class Account(AbstractBaseUser):

    # username_validator = UnicodeUsernameValidators
    first_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True, db_index=True)
    last_name = models.CharField(max_length=50)
    phone_number = models.IntegerField(null=True)
    email = models.EmailField(max_length=100, unique=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ["first_name", "last_name", "username", ]
    objects = MyAccountManager()

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_module):
        return True

    def __str__(self) -> str:
        return self.first_name


class UserProfile(models.Model):
    user = models.OneToOneField(
        Account, on_delete=models.CASCADE, related_name="profile", blank=True, null=True)
    location = models.CharField(max_length=50, null=True, blank=True)
    profile_pix = models.ImageField(
        upload_to="profile/profile_photo", default=None, blank=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)

    def get_absolute_url(self):
        return reverse("profile", kwargs={"pk": self.pk})

    def __str__(self) -> str:
        return self.user.first_name

contact/forms.py
from django import forms

from .models import Contact, CsvDoc


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ["first_name", "last_name",
                  "gender", "category", "contact_avatar"]

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields["first_name"].widget.attrs["class"] = "mt-1 focus: ring-indigo-500 focus: border-indigo-500 block w-full shadow-sm sm: text-sm border-indigo-300 rounded-md"
        self.fields["last_name"].widget.attrs["class"] = "mt-1 focus: ring-indigo-500 focus: border-indigo-500 block w-full shadow-sm sm: text-sm border-indigo-300 rounded-md"
        self.fields["category"].widget.attrs["class"] = "mt-1 focus: ring-indigo-500 focus: border-indigo-500 block w-full shadow-sm sm: text-sm border-indigo-300 rounded-md"
        self.fields["contact_avatar"].widget.attrs["class"] = "mt-1 focus: ring-indigo-500 focus: border-indigo-500 block w-full shadow-sm sm: text-sm border-indigo-300 rounded-md"
        self.fields["gender"].widget.attrs["class"] = "mt-1 focus: ring-indigo-500 focus: border-indigo-500 block w-full shadow-sm sm: text-sm border-indigo-300 rounded-md"


class CsvForm(forms.ModelForm):
    class Meta:
        model = CsvDoc
        fields = ["file_name", ]

    def __init__(self, *args, **kwargs):
        super(CsvForm, self).__init__(*args, **kwargs)

        self.fields["file_name"].widget.attrs["class"] = "mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm: text-sm border-indigo-300 rounded-md"

    def clean(self):
        cleaned_data = super(CsvForm, self).clean()
        file_name = cleaned_data.get('file_name')

contact/views.py
import csv
from django.shortcuts import render, get_object_or_404, HttpResponse, HttpResponseRedirect, redirect
from django.views import View
from django.views.generic import TemplateView, DeleteView, UpdateView, DetailView, CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.http import JsonResponse


from account.models import Account
from .forms import ContactForm, CsvForm
from .models import Contact, CsvDoc

# Create your views here.


class HomeView(ListView):
    template_name = "contact/index.html"
    context_object_name = 'contacts'
    model = Contact

    def get_queryset(self):
        print(self.request.user.profile)
        contacts = super().get_queryset().filter(manager=self.request.user)
        print(contacts)
        return contacts


def home(request):
    print(request.user)
    if request.user.is_authenticated:
        context = {
            "all_contact": Contact.objects.all().count(),
            "male_contacts": Contact.objects_gender.male().filter(manager=request.user).count(),
            "female_contacts": Contact.objects_gender.female().filter(manager=request.user).count(),
            "non_binary": Contact.objects_gender.non_binary().filter(manager=request.user).count(),
            "family_count": Contact.objects_category.family().filter(manager=request.user).count(),
            "friends_count": Contact.objects_category.friends().filter(manager=request.user).count(),
            "work_count": Contact.objects_category.work().filter(manager=request.user).count(),
            "family": Contact.objects_category.family().filter(manager=request.user),
            "friends": Contact.objects_category.friends().filter(manager=request.user),
            "work": Contact.objects_category.work().filter(manager=request.user),
            "all_contacts": Contact.objects.all(),
            "personal_contacts_count": Contact.objects.filter(manager=request.user).count(),
            "personal_contacts": Contact.objects.filter(manager=request.user),
        }
        return render(request, "contact/index.html", context)
    else:
        context = {
            "personal_contacts": "Welcome"
        }
    return render(request, "contact/home.html", context)


# class HomeView(ListView):
#     template_name = "contact_app/index.html"
#     context_object_name = 'contacts'
#     model = Contact

#     def get_queryset(self):
#         return super().get_queryset().filter(manager=self.request.user)


class ContactCreateView(LoginRequiredMixin, CreateView):
    model = Contact
    form_class = ContactForm
    template_name = 'contact/create_contact.html'
    # fields = ['first_name', 'email', 'phone', 'info', 'gender', 'image']

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.manager = self.request.user
        instance.save()
        messages.success(
            self.request, 'Your contact has been successfully created!')
        return redirect('home')


class ContactUpdateView(LoginRequiredMixin, UpdateView):
    form_class = ContactForm
    model = Contact
    template_name = 'contact/contact_update.html'
    login_url = 'login'

    def form_valid(self, form):
        instance = form.save()
        messages.success(
            self.request, 'Your contact has been successfully updated!')
        return redirect('contact-detail', args=[instance.pk])


class ContactDetailView(LoginRequiredMixin, DetailView):
    template_name = 'contact/contact_detail.html'
    model = Contact
    context_object_name = 'contact'

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)


def contacts_overview(request):

    context = {
        "all_contact_count": Contact.objects.all().count(),
        "male_contacts": Contact.objects_gender.male().count(),
        "female_contacts": Contact.objects_gender.female().count(),
        "non_binary": Contact.objects_gender.non_binary().count(),
        "family_count": Contact.objects_category.family().filter(manager=request.user).count(),
        "friends_count": Contact.objects_category.friends().filter(manager=request.user).count(),
        "work_count": Contact.objects_category.work().filter(manager=request.user).count(),
        "family": Contact.objects_category.family().filter(manager=request.user),
        "friends": Contact.objects_category.friends().filter(manager=request.user),
        "work": Contact.objects_category.work().filter(manager=request.user),
        "all_contacts": Contact.objects.all(),
        "personal_contacts_count": Contact.objects.filter(manager=request.user).count(),
        "personal_contacts": Contact.objects.filter(manager=request.user),
    }
    return render(request, "contact/contacts_overview.html", context)


# class ContactDeleteView(LoginRequiredMixin, View):
#     def get(self, request, pk, *args, **kwargs):
#         if request.is_ajax():
#             contact = Contact.objects.filter(pk=pk)
#             contact.delete()
#             return JsonResponse({"message":"success"})
#         return JsonResponse({"message": "success"})
class ContactDeleteView(LoginRequiredMixin, DeleteView):
    model = Contact
    template_name = 'delete.html'
    success_url = reverse_lazy('home')

    def delete(self, request, *args, **kwargs):
        messages.success(
            self.request, 'Your contact has been successfully deleted!')
        return super().delete(self, request, *args, **kwargs)


@login_required(login_url='login')
def SearchView(request):
    if request.method == 'POST':
        kerko = request.POST.get('search')
        print(kerko)
        results = Contact.objects.filter(first_name__contains=kerko)
        context = {
            'results': results
        }
        return render(request, 'users/search_result.html', context)


@login_required(login_url='login')
def list_favourites_contacts(request):
    user_id = request.user
    contacts = Contact.objects.filter(favourite=user_id)
    print(contacts)
    print(user_id.username)
    return render(request, "contact/favourite_contacts.html", {
        "contacts": contacts
    })


@login_required(login_url='login')
def add_contact_as_favourite(request, contact_pk):
    fav = False
    contact = get_object_or_404(Contact, pk=contact_pk)

    if contact.favourite.filter(id=request.user.id).exists():
        fav = False
        contact.favourite.remove(request.user)
        contact.save()

    else:
        contact.favourite.add(request.user)
        contact.save()
        fav = True
        context = {
            "fav": fav,
            "contact": contact
        }
    # return JsonResponse(resp, content_type="application/json")
    return redirect(request.META["HTTP_REFERER"])


def generate_contact_csv(request, account_pk):
    manager = Account.objects.get(pk=account_pk)
    resp = HttpResponse(content_type="text/csv")
    resp["Content-Disposition"] = 'attachment; filename=contacts.csv'
    # contacts = Contact.objects.all()
    contacts = Contact.objects.filter(manager__pk=account_pk)
    headers = ["first_name", "last_name", "manager", "gender", "category",
               "contact_avatar", "favourite", "date_created", "date_updated"]
    writer = csv.writer(resp)
    writer.writerow(headers)
    for contact in contacts:
        query = contact.favourite.filter(pk=account_pk)
        for attr in query:
            query = attr.username
            print(query)
        writer.writerow([contact.first_name, contact.last_name, contact.manager.username, contact.gender, contact.category,
                        contact.contact_avatar.path, query, contact.date_created, contact.date_updated])
    return resp


def import_csv(request, account_pk):

    if request.method == "POST":
        form = CsvForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            print("here")
            form.save()
            form = CsvForm()
            contact_list = []
            try:
                obj = CsvDoc.objects.get(activated=False)
                print(obj)
                with open(obj.file_name.path, 'r') as file:
                    reader = csv.reader(file)
                    for i, row in enumerate(reader):
                        if i == 0:
                            pass
                        else:
                            print(row[1])
                            import_account = Account.objects.get(pk=account_pk)
                            contact_list.append(Contact(first_name=row[0], last_name=row[1], manager=import_account,
                                                        gender=row[3], category=row[4], contact_avatar=row[5], date_created=row[7], date_updated=row[8]))
                            print(contact_list)
                contacts = Contact.objects.bulk_create(
                    contact_list)
                print("GGG")
                print(contacts)
                print(contact_list)
                obj.activated = True
                obj.save()
                messages.success(
                    request, "Your new Contacts import were successfully Created!🎉")
            except (TypeError, ValueError, OverflowError, Account.DoesNotExist) as e:
                print(e)

            return redirect('all-contacts')
        else:
            print(form.errors)
            messages.error(
                request, "Contacts import error")
            form = CsvForm(request.POST, request.FILES)
            return render(request, "contact/import_csv_form.html", {
                'form': form,
            })
    else:
        form = CsvForm()
        return render(request, "contact/import_csv_form.html", {
            'form': form,
        })

contact/templates/contact/favourite_contacts.html
{% extends 'account/base.html' %}
{% load static tailwind_tags %}
{% tailwind_preload_css  %}
{% tailwind_css %}


{% block content %}
<div>


          <!-- Favourite Contacts list -->
          <div class="mt-8 max-w-5xl mx-auto px-4 pb-12 sm:px-6 lg:px-8">
            <h2 class="text-sm font-medium text-gray-500">Favourite Contacts</h2>
    
            <div class="mt-1 grid grid-cols-1 gap-4 sm:grid-cols-2">
               {% for fav_contact in contacts %}
              <div class="relative rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm flex items-center space-x-3 hover:border-gray-400 focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-pink-500">
                <div class="flex-shrink-0">
                  <img class="h-10 w-10 rounded-full" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
                </div>
                <div class="flex-1 min-w-0">
                  <a href="{% url "contact-detail" fav_contact.pk %}" class="focus:outline-none">
                    <span class="absolute inset-0" aria-hidden="true"></span>
                    <p class="text-sm font-medium text-gray-900">{{fav_contact}}</p>
                    <p class="text-sm text-gray-500 truncate">{{fav_contact.gender}}</p>
                  </a>
                </div>

                {% comment %} {% if fav %} {% endcomment %}
                     <a href="{% url "favourite" fav_contact.pk %}" class="text-indigo-600 hover:text-indigo-900">Remove from Favourites</a>
                {% comment %} {% endif %} {% endcomment %}
              </div>
              {% endfor %}
            </div>
            
        </div>


</div>

{% endblock content %}

contact/templates/contact/import_csv_form.html
{% extends 'account/base.html' %}
{% load static %}
{% load tailwind_tags %}

{% tailwind_css %}
{% block css_content %}
   <style>
      
    @keyframes notify{
      0%{top:-100%}
      25%{top:50%}
      50%{top:50%}
      100%{top:-100%}
    }
    .show-message{
      position: absolute;
      top:100%;
      left:20px;
      animation: notify 7s;
    }
    #id_profile_pix, #profile_pix-clear_id {
      border-radius:5px;
      outline:2px solid transparent
      border-color: indigo;
    }
    </style>
{% endblock css_content %}
  
{% block content %}
<div  class="max-h-full w-full flex items-center justify-center box-content mt-20 sm:mt-0">
  <div class="flex-row w-2/4 h-full">
        <div class="md:col-span-1 m-35">
          <div class="px-4 sm:px-0 m-10">
              <h3 class="text-lg font-medium leading-6 text-gray-900">Import Contact as CSV File</h3>
              <p class="mt-1 text-sm text-gray-800">Update Your Profile.</p>
          </div>
        </div>
    <div class="mt-10 md:mt-0 md:col-span-2 bg-cyan-600 flex-auto items-center justify-center rounded">
      
      <form action="{% url 'import-contacts' request.user.pk %}" method="POST" enctype="multipart/form-data">
       {% csrf_token %}
        <div class="shadow overflow-hidden sm:rounded-lg">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="md:col-span-1 m-35">
              
          <div class="px-4 sm:px-0 m-10 flex justify-between">
              <h3 class="text-lg font-medium leading-6 text-gray-900">Import</h3>
            <img class="block h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg" alt="Workflow">
            <p class="text-gray-800 mx-3 font-black">Contactly</p>
            
          </div>
        </div>
         {% if form.errors %}
            <div class="rounded-md bg-red-50 p-4 show-message">
                    <div class="flex">
                            <div class="flex-shrink-0">
                            <!-- Heroicon name: solid/x-circle -->
                                    <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
                                    </svg>
                            </div>
                            <div class="ml-3">
                                <h3 class="text-sm font-medium text-red-800">Error</h3>
                                <div class="mt-2 text-sm text-red-700">
                                    <ul role="list" class="list-disc pl-5 space-y-1">
                                      {% for field in form %}
                                    {% for error  in field.errors %}
                                        <li>{{ error}}🙄</li>
                                      {% endfor %}
                                    {% endfor %}
                                    </ul>
                                </div>
                            </div>
                    </div>
            </div>
            {% endif %}

             {% if messages %}
               {% for message  in messages %}
                    {% if message.tags == "error" %}
                    <div class="rounded-md bg-red-50 p-4 show-message">
                    <div class="flex">
                            <div class="flex-shrink-0">
                            <!-- Heroicon name: solid/x-circle -->
                                    <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
                                    </svg>
                            </div>
                            <div class="ml-3">
                                <h3 class="text-sm font-medium text-red-400">Error</h3>
                                <div class="mt-2 text-sm text-red-400">
                                    <ul role="list" class="list-disc pl-5 space-y-1">
                                  
                                    <p>{{ message }}🎉</p>
                                    </ul>
                                </div>
                            </div>
                    </div>
            </div>
                    {% else %}
                    <div class="rounded-md bg-green-50 p-4 show-message">
                    <div class="flex">
                            <div class="flex-shrink-0">
                            <!-- Heroicon name: solid/x-circle -->
                                    <svg class="h-5 w-5 text-green-300" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                                        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
                                    </svg>
                            </div>
                            <div class="ml-3">
                                <h3 class="text-sm font-medium text-green-300">Success</h3>
                                <div class="mt-2 text-sm text-green-300">
                                    <ul role="list" class="list-disc pl-5 space-y-1">
                                  
                                    <p>{{ message }} {{message.tags}}🎉</p>
                                      
                                    </ul>
                                </div>
                            </div>
                    </div>
            </div>
                    {% endif %}
          {% endfor %}
            
    {% endif %}

          
                <div class="sm:col-span-6">
                  <label for="cover-photo" class="block text-sm font-medium text-gray-700">Import File</label>
                  <div class="mt-1 flex justify-center px-6 pt-5 pb-6 border-2 border-gray-300 border-dashed rounded-md">
                    <div class="space-y-1 text-center">
                      <svg class="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
                        <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
                      </svg>
                      <div class="flex text-sm text-gray-600">
                        <label for="file-upload" class="relative cursor-pointer bg-white rounded-md font-medium text-indigo-600 hover:text-indigo-500 focus-within:outline-none focus-within:ring-2 focus-within:ring-offset-2 focus-within:ring-indigo-500">
                          <span>Upload a file</span>
                          {{form.file_name}}
                        </label>
                        <svg class="flex-shrink-0 h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path fill-rule="evenodd" d="M8 4a3 3 0 00-3 3v4a5 5 0 0010 0V7a1 1 0 112 0v4a7 7 0 11-14 0V7a5 5 0 0110 0v4a3 3 0 11-6 0V7a1 1 0 012 0v4a1 1 0 102 0V7a3 3 0 00-3-3z" clip-rule="evenodd" />
                </svg>
                        <p class="pl-1">or drag and drop</p>
                      </div>
                      <p class="text-xs text-gray-500">Only CSV up to 10MB, (PNG, JPG, GIF are not supported)</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
            <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-500 hover:bg-indigo-900 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">Import File</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}
  